# nixpacks.toml

[phases.setup]
# Estos paquetes proporcionan pg_config y un compilador
packages = [
  "postgresql", 
  "gcc"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
# Ajusta el comando de inicio según tu proyecto (gunicorn, etc.)
cmd = "gunicorn Enruta.wsgi:application --bind 0.0.0.0:$PORT"
