# Generated by Django 5.1.7 on 2025-03-20 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furgones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furgon',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furgones', to='furgones.conductor'),
        ),
    ]
